### ISSUE TITLE
Expose REST server port

### ISSUE THREAD

**Issue by antaenc** [Senzing/docker-web-app-demo#39]
Add exposure of the REST server port to the demo. Helpful to use the Web App plus the REST server for demos and for customers. 

In the output logging also add the Swagger editor link as per ./docker-bin/senzing-api-server.sh  for example as a reference: 
```
==============================================================================
== senzenvtest-api-server running on http://192.168.1.69:8250
== Swagger editor: http://editor.swagger.io/?url=https://raw.githubusercontent.com/Senzing/senzing-rest-api-specification/master/senzing-rest-api.yaml
==============================================================================
```

**Comment by docktermj** [comment]
To do this:

1) Change https://github.com/Senzing/docker-web-app-demo/blob/b18b7144c9ad12b088fcec765cc5397facacca13/rootfs/etc/supervisord.conf#L144 to 
```
command = java -jar senzing-api-server.jar -concurrency 10 -httpPort 8250 -bindAddr all -iniFile /etc/opt/senzing/G2Module.ini -allowedOrigins "*" -enableAdmin
```

2) Change https://github.com/Senzing/docker-web-app-demo/blob/b18b7144c9ad12b088fcec765cc5397facacca13/Dockerfile#L87 to
```
ENV SENZING_API_SERVER_URL="http://localhost:8250"
```

3) Before this line: https://github.com/Senzing/docker-web-app-demo/blob/b18b7144c9ad12b088fcec765cc5397facacca13/Dockerfile#L73 add
```
EXPOSE 8250
```

The test:
1. Bring up the docker container
1. Verify that the web app is seen on port 8251
1. Verify that the API server is accessable on port 8250.  Example:
```console
curl -X GET http://localhost:8250/heartbeat
```

**Comment by docktermj** [comment]
After this change is made, make the change in https://github.com/Senzing/senzing-environment/issues/35
